#!/bin/bash

#
# CONFIG
###################
NO_KEY="-o PubKeyAuthentication=no"
ANON_HOST="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
USAGE_TITLE="SSH Toolkit"
SSH="$( which ssh )"
SCP="$( which scp )"
SSHFS="$( which sshfs )"
UNMOUNT="$( which fusermount ) -u "
PORT=22
_REF_FORMAT="name|alias|ip-address:port"

#
# USE REQUIRE
###################
source $( dirname -- "$0" )/lib/require.sh $*

#
# COMMANDS
###################
COMMANDS=(
  SSH
  SCP
  SSHFS
)

#
# HOSTS
###################
HOSTS=(
  cfz-nas-1=root@10.10.15.20
  cfz-nas-12=10.10.15.30:2222
  grapevine1=10.10.255.1
  grapevine2=10.10.255.2
  peach=10.10.255.201
  grape=10.10.255.211
  melon=10.10.255.221
  peach-comfreeze=comfreeze@10.10.255.201
  peach-impekable=impekable@10.10.255.201
)

##sshfs ${OPTS} comfreeze@10.10.15.201:'/home/comfreeze' ~/peach
##sshfs ${OPTS} impekable@10.10.15.201:'/home/impekable' ~/peach-impekable
#
# MOUNTS
###################
MOUNTS=(
  cfz-nas-1='/data/'
  cfz-nas-12='/'
  grapevine1='.'
  grapevine2='.'
  peach='.'
  grape='.'
  melon='.'
  peach-comfreeze='/home/comfreeze'
  peach-impekable='/home/impekable'
)

#
# LIBRARIES
###################
require array
require string
#require params
#require actions

#
# CUSTOM METHODS
###################
_apply_options () {
  dump_method $*
  apply_options COMMANDS $*;
}

add_host () {
  dump_method $*
  echo "Coming soon.";
}

action_connect () {
  dump_method $*
  apply_option SSH "$( verboses )"
  HOST=$( filter_array HOSTS ${1} ); shift
  if [ ! -z "${HOST}" ]; then
    echo "Connecting to ${HOST}"
    OPTS=( $( explode_array ":" ${HOST} ) )
    if (( "${#OPTS[@]}" >= "2" )); then
      HOST="${OPTS[0]}"; _PORT="${OPTS[1]}";
      [ ! -z "${_PORT}" ] && prepend_option HOST "-p ${_PORT}"
    fi
    verbose 0 ${SSH} ${HOST}
    ${SSH} ${HOST}
  else
    echo "Raw connect to parameters to $*"
    verbose 0 ${SSH} $*
    ${SSH} $*
  fi
}

mount () {
  dump_method $*
  for TARGET in "$@"; do
    HOST=$( filter_array HOSTS ${TARGET} )
    MOUNT=$( filter_array MOUNTS ${TARGET} )
    if [ ! -z "${HOST}" ]; then
      echo "Mounting ${HOST} => ~/${TARGET}"
      OPTS=( $( explode_array ":" ${HOST} ) )
      if (( "${#OPTS[@]}" >= "2" )); then
        HOST="${OPTS[0]}"; _PORT="${OPTS[1]}";
        [ ! -z "${_PORT}" ] && prepend_option HOST "-o port=${_PORT}"
      fi
      verb 2 prepend_option HOST "-d -o sshfs_debug -o workaround=all"
      verb 1 apply_option SSHFS "-o ssh_command=\"${SSH} $( verboses )\" "
      verbose 1 ${SSHFS} ${HOST}:${MOUNT} ~/${TARGET}
      ${SSHFS} ${HOST}:${MOUNT} ~/${TARGET}
    fi
  done
}

unmount () {
  dump_method $*
  for TARGET in "$@"; do
    MOUNT=$( filter_array MOUNTS ${TARGET} )
    if [ ! -z "${MOUNT}" ]; then
      verbose 0 "Unmounting ~/${TARGET}"
      verbose 1 ${UNMOUNT} ~/${TARGET}
      ${UNMOUNT} ~/${TARGET}
    fi
  done
}

remount () {
  dump_method $*
  unmount $*
  mount $*
}

#
# PARAMETERS
###################
# Anonymity
usage_anonymous ()      { echo "-a|--anonymous"; }
describe_anonymous ()   { echo "Support anonymous hosts, ignore host checks."; }
param_anonymous ()      { _apply_options "${ANON_HOST}"; }
help_anonymous ()       { echo "More detailed help here."; }
# Identity
usage_no_key ()         { echo "-n|--no-key"; }
describe_no_key ()      { echo "Disable public key based authentication methods."; }
param_no_key ()         { _apply_options "${NO_KEY}"; }
help_no_key ()          { echo "More detailed help here."; }
# Port
usage_port ()           { echo "-p|--port ####"; }
describe_port ()        { echo "Specify a custom port to use for connections."; }
param_port ()           { _PORT="$1"; }
help_port ()            { echo "More detailed help here."; }
# Overwrite Faking
param_fake ()           { prepend_options COMMANDS "echo "; }

#
# ACTION
###################
# Define a new Host Record
usage_add_host ()       { echo "a|add|add_host ${_REF_FORMAT}"; }
describe_add_host ()    { echo "Define a new host record"; }
action_add_host ()      { add_host $*; }
help_add_host ()        { echo "More detailed help here."; }
# Connect to a target
usage_connect ()        { echo "c|connect ${_REF_FORMAT}"; }
describe_connect ()     { echo "Connect to a defined host"; }
#action_connect ()       { connect $*; }
help_connect ()         { echo "More detailed help here."; }
# Mount a target
usage_mount ()          { echo "m|mount ${_REF_FORMAT}"; }
describe_mount ()       { echo "Mount a defined host share"; }
action_mount ()         { mount $*; }
help_mount ()           { echo "More detailed help here."; }
# Unmount a target
usage_unmount ()        { echo "u|unmount ${_REF_FORMAT}"; }
describe_unmount ()     { echo "Unount a defined host share"; }
action_unmount ()       { unmount $*; }
help_unmount ()         { echo "More detailed help here."; }
# Remount a target
usage_remount ()        { echo "r|remount ${_REF_FORMAT}"; }
describe_remount ()     { echo "Remount a defined host share"; }
action_remount ()       { remount $*; }
help_remount ()         { echo "More detailed help here."; }

#
# LOGIC
###################
require help $*
run $*
